platform :ios, '11.0'
use_frameworks!

target 'VK_client' do

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod "PromiseKit", "~> 6.8"

end
